[package]
name = "digger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
lazy_static = "1.5.0"
questdb-rs = "4.0.3"
serde = "1.0.218"
serde_json = "1.0.140"
thirtyfour = "0.35.0"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
