[xueqiu]
detail_url = "https://stock.xueqiu.com/v5/stock/quote.json?extend=detail"
industry_url = "https://xueqiu.com/stock/industry/stockList.json?type=1&size=100"
minute_url = "https://stock.xueqiu.com/v5/stock/chart/minute.json"

[test]
detail_url = "https://test.com"
industry_url = "https://test.com"
minute_url = "https://test.com"

[chromewebdriver]
endpoint = "http://localhost"
port = 51611

[questdb]
endpoint = "http::addr=localhost:9000;"
